### PR TITLE
[FEAT] support acl protected consul servers

### PR DESCRIPTION
**Pull request by blockchainjamie**
I've been looking for a sensible way to monitor Nomad periodic jobs and I was glad to find this project, this PR adds support for consul servers that are running the ACL system. Please let me know if you would like me to make any changes.

### CODE REVIEW

**Comment by sepulworld** [comment]
Thank you! I will review, merge and cut new release this weekend.

**Comment by sepulworld** [comment]
Since you gave me access to the branch for the patch, I'm going to make some small changes. Then let me know what you think! Since there are other tokens (Slack in this case), I'm updating the variables to consul_token. Fixing the tests a bit, I think we can default to having the token be an empty string?

**Comment by sepulworld** [comment]
> Since you gave me access to the branch for the patch, I'm going to make some small changes. Then let me know what you think! Since there are other tokens (Slack in this case), I'm updating the variables to consul_token. Fixing the tests a bit, I think we can default to having the token be an empty string?

Nevermind, we can skip adding the header value on the default "" empty value. Ill merge and tag this. Worked well locally for me and tests pass now. Let me know how it goes

**Comment by sepulworld** [comment]
https://rubygems.org/gems/deadman_check/versions/0.3.1

**Comment by blockchainjamie** [comment]
That's great, thanks very much for looking at this 👍

**Pull request merged**
